---
title: C6312 | Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: cbfba91ef4b41c2789713f423db0db3544db045d
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 08/22/2018
ms.locfileid: "47578901"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

La versión más reciente de este tema puede encontrarse en [C6312](https://docs.microsoft.com/visualstudio/code-quality/c6312).  
  
Advertencia C6312: posible bucle infinito: uso de la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-excepto  
  
 Esta advertencia indica que el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como -1) en la expresión de filtro de controlador de excepciones estructurado. Uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría dar lugar a un bucle infinito. Por ejemplo, si se generó una excepción por hardware, se reiniciará la instrucción que produjo la excepción. Si la dirección que produjo la excepción sigue siendo incorrecta, otro tipo de excepción se producirá y administrarse de la misma manera. Esto hace que un bucle infinito.  
  
 Una llamada explícita a `RaiseException` directamente no le causa un bucle infinito, pero continuará la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si `RaiseException` se usó para evitar la desreferenciación de un puntero no válido.  
  
 Por lo general, `EXCEPTION_CONTINUE_EXECUTION` debe devolver una función llamada en la expresión de filtro, que tiene la oportunidad de corregir, ya sea el puntero que produjo la excepción o la memoria subyacente.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Para corregir esta advertencia, utilice el código siguiente:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```



