---
title: C28125 | Documentos de Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C28125
helpviewer_keywords: C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: "4"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: 0ccd458c57468e3dc5f7ea7e56cc6f210eabec80
ms.sourcegitcommit: fb751e41929f031d1a9247bc7c8727312539ad35
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/15/2017
---
# <a name="c28125"></a>C28125
Advertencia C28125: la funci贸n se debe invocar desde dentro de un bloque try / except bloque  
  
 El controlador llama a una funci贸n que se debe invocar desde dentro de un bloque try / except bloque, como [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Ejemplo  
 El siguiente c贸digo de ejemplo genera esta advertencia:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 El siguiente c贸digo de ejemplo evita esta advertencia:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```