---
title: C28125 | Documentos de Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: 5fbaf9517096c6f420947e779658632066c4358d
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/22/2017
---
# <a name="c28125"></a>C28125
Advertencia C28125: la funci贸n se debe invocar desde dentro de un bloque try / except bloque  
  
 El controlador llama a una funci贸n que se debe invocar desde dentro de un bloque try / except bloque, como [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Ejemplo  
 El siguiente c贸digo de ejemplo genera esta advertencia:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 El siguiente c贸digo de ejemplo evita esta advertencia:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```