---
title: C28125
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 271ac2aece4566ca0c6cc952339805f62dc77796
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/26/2018
---
# <a name="c28125"></a>C28125
Advertencia C28125: la funci贸n se debe invocar desde dentro de un bloque try / except bloque

 El controlador llama a una funci贸n que se debe invocar desde dentro de un bloque try / except bloque, como [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).

## <a name="example"></a>Ejemplo
 El siguiente c贸digo de ejemplo genera esta advertencia:

```
ProbeForRead(addr, len, 4);
```

 El siguiente c贸digo de ejemplo evita esta advertencia:

```

__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```